name: Github Actions - teste

on: 
    push

jobs: 
    action-lint:
        name: Lint do código no push
        runs-on: ubuntu-latest
        steps: 
            - run: echo "Job iniciado por evento ${{ github.event_name }}."

            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: Super-Linter
              uses: super-linter/super-linter@v6.6.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Test with the dotnet CLI
              run: dotnet test
            

        
